# minimumReleaseAge: 4320 # 3 days
resolutionMode: "highest"
packages:
  - "packages/*"
  - "examples/*"
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  detox: true
  dtrace-provider: true
  esbuild: true
  sharp: true
