# minimumReleaseAge: 4320 # 3 days
resolutionMode: "highest"
packages:
  - "packages/*"
  - "examples/*"
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  detox: true
  dtrace-provider: true
  esbuild: true
  sharp: true
overrides:
  h3@<=1.15.8: ^1.15.9
  iltorb: npm:noop2@^2.0.0
  lodash@<=4.17.23: ^4.18.0
  node-forge@<=1.4.0: ^1.4.0
  serialize-javascript@<=7.0.5: ^7.0.5
  srvx@<0.11.13: ^0.11.13
  vite@<=7.3.2: ^7.3.2 || ^8.0.7
  '@xmldom/xmldom@<=0.8.13': 0.8.13
  uuid@<=11.1.1: 11.1.1
  minimatch@<=5.0.1: ^9.0.0
  undici@<=7.26.0: 7.26.0
  '@turbo/darwin-64@<=2.9.15': 2.9.15
  '@turbo/windows-64@<=2.9.15': 2.9.15
  esbuild@<=0.28.1: 0.28.1
