name: Publish to pub.dev

on:
  push:
    branches:
      - main
    paths:
      - "ECMAScript/react-native/CHANGELOG.md" # piggyback from react-native changelog

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using GitHub-signed OIDC token
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.0.6"
      - uses: flutter-actions/setup-flutter@v2
        with:
          version: "3.10.6"
          channel: "stable"
          cache: true
          cache-key: ${{ runner.tool_cache }}/flutter # optional, change this to force refresh cache
      - name: Install dependencies
        run: flutter pub get
      - name: Setup Pub Credentials
        shell: bash
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
          PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
        run: |
          sh ./pub_login.sh
      - name: Check Publish Warnings
        run: flutter pub publish --dry-run
      # - name: Publish Package
      #   run: flutter pub publish -f
