---
name: quiltt_connector
description: A Flutter SDK for Quiltt Connector, support iOS and Android.
version: 5.2.0
homepage: https://quiltt.io/
repository: https://github.com/quiltt/quiltt-sdks/tree/main
environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.38.0"
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: "^4.4.1"
  url_launcher: "^6.1.14"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
