name: Bundlewatch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  bundlewatch:
    name: Check bundle size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-js

      - name: Check bundle size
        run: pnpm bundlesize
