name: Check TODOs
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-todos:
    name: Check Outstanding TODOs
    runs-on: ubuntu-latest
    steps:
      - name: Check for incomplete task list items
        uses: Shopify/task-list-checker@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
