name: Test
on:
  push:
    branches:
      - main
    paths:
      - packages/core/src/*
      - packages/core/tests/*
      - packages/react/src/*
      - packages/react/tests/*
      - packages/react-native/src/*
      - packages/react-native/tests/*
  pull_request:
    paths:
      - packages/core/src/*
      - packages/core/tests/*
      - packages/react/src/*
      - packages/react/tests/*
      - packages/react-native/src/*
      - packages/react-native/tests/*
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Build packages
        uses: pnpm run build

      - name: Run tests
        run: pnpm run test

      - name: Collect code coverage and upload to CodeClimate
        uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pnpm run coverage
