name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Collect code coverage and upload to CodeClimate
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pnpm run coverage
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov

      - name: Run tests on example apps
        run: pnpm test

      - if: ${{ failure() }}
        name: Upload Error Screenshot
        uses: actions/upload-artifact@v3
        with:
          name: error_screenshots
          path: |
            ${{github.workspace}}/**/cypress/screenshots
            ${{github.workspace}}/**/cypress/videos
          retention-days: 3
